POST http://localhost:3100/auth/signup
Content-Type: application/json

{
	"nickname": "test",
	"email": "test@test.com",
	"password": "password"
}

###
GET http://localhost:3100/auth/login
Content-Type: application/json

{
	"email": "test@test.com",
	"password": "password"
}

###
POST http://localhost:3100/auth/token/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjFiMGM4MS0xMjJjLTQ5YjMtOGVhYy1lNDk0OTczZGQ5ZjQiLCJpYXQiOjE3MzIxNTQ1MzgsImV4cCI6MTczMjE1ODEzOH0.dXtff1VB2ejJlvY7TJszD1Pdr_rgPtzxy5E9UgX3s8g
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyZjFiMGM4MS0xMjJjLTQ5YjMtOGVhYy1lNDk0OTczZGQ5ZjQiLCJpYXQiOjE3MzIxNTQ1MzgsImV4cCI6MTczMzM2NDEzOH0.Pyul96QLYAZUDUdv3ZV_jgWbMPQCl0w6s7R3Phj6Xtw; Max-Age=1209600; Path=/token/refresh; Expires=Thu, 05 Dec 2024 02:02:18 GMT; HttpOnly; Secure; SameSite=None
