// 교환 제안
POST http://localhost:3100/cards/d38935b4-73b4-4273-9c8f-1e84d812fd65/exchange
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1M2ExMGFkNS01YzdhLTQ0MTUtOTY4My1hMTUxYjg2MWIyNmQiLCJpYXQiOjE3MzI5MDY4NDIsImV4cCI6MTczNDExNjQ0Mn0.VVkug4vfkrNdy4WXEN-oxMWGo0qZUK2qy9K2GLpITgw
Content-Type: application/json

{
  "buyerCardId": "6b727387-8425-4e11-95dd-ff86890811c0",
  "description": "마릴"
}

###
// 교환 승인
POST http://localhost:3100/cards/exchange/f3512d89-c991-43bf-8cfc-02d8084e0440/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNjRhMDI0Zi1lZWI1LTQzNDEtODhjMi0yMjU5YWEwYmYwY2UiLCJpYXQiOjE3MzI5MDc2MzgsImV4cCI6MTczNDExNzIzOH0.Erz8rCVovnE6SHbYpVSbh2NJaE2icVx2Wg0s2Hjc70U
Content-Type: application/json


###
// 교환 거절
DELETE http://localhost:3100/cards/exchange/fb016066-069f-4e83-8144-d1e08a6f8c76/refuse
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzNjRhMDI0Zi1lZWI1LTQzNDEtODhjMi0yMjU5YWEwYmYwY2UiLCJpYXQiOjE3MzI5MDc2MzgsImV4cCI6MTczNDExNzIzOH0.Erz8rCVovnE6SHbYpVSbh2NJaE2icVx2Wg0s2Hjc70U



###
// 교환 취소
DELETE http://localhost:3100/cards/exchange/442de325-0afc-4ea7-a5cf-67a8fa7e568c/cancel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1M2ExMGFkNS01YzdhLTQ0MTUtOTY4My1hMTUxYjg2MWIyNmQiLCJpYXQiOjE3MzI5MDY4NDIsImV4cCI6MTczNDExNjQ0Mn0.VVkug4vfkrNdy4WXEN-oxMWGo0qZUK2qy9K2GLpITgw
