### 랜덤 포인트 뽑기 요청 (POST)
POST http://localhost:3100/api/points/box
Content-Type: application/json

{
  "userId": "e6cd05c6-34d5-4871-82c1-f882988d0ece"
}

### 마지막 뽑기 시간 조회 요청 (GET)
GET http://localhost:3100/api/points/last-draw-time?userId=e6cd05c6-34d5-4871-82c1-f882988d0ece
