### 랜덤 포인트 뽑기 요청 (POST)
POST http://localhost:3100/points/box
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1M2ExMGFkNS01YzdhLTQ0MTUtOTY4My1hMTUxYjg2MWIyNmQiLCJpYXQiOjE3MzI4MTA2MjMsImV4cCI6MTczMjg5NzAyM30.UsASegRgmaQgW2Z9JcLM9HFtP0jlPkSyKSzS4AhAzqA


### 마지막 뽑기 시간 조회 요청 (GET)
GET http://localhost:3100/points/last-draw-time
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1M2ExMGFkNS01YzdhLTQ0MTUtOTY4My1hMTUxYjg2MWIyNmQiLCJpYXQiOjE3MzI2OTUxOTksImV4cCI6MTczMzkwNDc5OX0.T59BlDElKt57YZlcQJrZZ-crjIk_17VCaaTGptQ9SKs
