GET http://localhost:3100/shop/cards?filter[type]=type&filter[value]=독

###
GET http://localhost:3100/shop/cards/cards/5b48ef91-4238-484e-a91f-8f889859bbdb

###
POST http://localhost:3100/shop/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNmZiMzlkNi0wZmNjLTRiMjMtOTg3YS0xZTAzYjIzYzJkOWYiLCJpYXQiOjE3MzIxNjc3OTUsImV4cCI6MTczMjE3MTM5NX0.r4PrKaKTj3jLyMARAtK-e7PBD7NJSUjY8cjfrPzp6m0
Content-Type: application/json

{
	"price": 5,
	"quantity": 3,
	"exchangeGrade": "LEGENDARY",
	"exchangeType": "Card",
	"exchangeDetails": "교환",
	"cardId": "32e9359c-fd10-44d8-bab4-e4c9cf28a87c"
}

###
PATCH http://localhost:3100/shop/cards/c11737c0-a283-43b4-9f13-b26d1ce78758
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNmZiMzlkNi0wZmNjLTRiMjMtOTg3YS0xZTAzYjIzYzJkOWYiLCJpYXQiOjE3MzIxNjc3OTUsImV4cCI6MTczMjE3MTM5NX0.r4PrKaKTj3jLyMARAtK-e7PBD7NJSUjY8cjfrPzp6m0
Content-Type: application/json

{
	"price": 6
}

###
DELETE http://localhost:3100/shop/cards/6e99849c-bd9d-4d23-a8e9-2f269c81132d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNmZiMzlkNi0wZmNjLTRiMjMtOTg3YS0xZTAzYjIzYzJkOWYiLCJpYXQiOjE3MzIxNjc3OTUsImV4cCI6MTczMjE3MTM5NX0.r4PrKaKTj3jLyMARAtK-e7PBD7NJSUjY8cjfrPzp6m0

###
POST http://localhost:3100/shop/cards/9b5a14eb-7f0b-4ad8-ae54-c3a9e97f2d1b/purchase
