GET http://localhost:3100/shop/cards?filter[type]=type&filter[value]=독

###
GET http://localhost:3100/shop/cards/9b5a14eb-7f0b-4ad8-ae54-c3a9e97f2d1b

###
POST http://localhost:3100/shop/cards
Content-Type: application/json

{
	"price": 5,
	"quantity": 3,
	"exchangeGrade": "LEGENDARY",
	"exchangeType": "Card",
	"exchangeDetails": "교환",
	"sellerId": "efbea72e-0fd0-49b0-8ec5-bcf3eaf5e335",
	"cardId": "32e9359c-fd10-44d8-bab4-e4c9cf28a87c"
}

###
PATCH http://localhost:3100/shop/cards/1ade0a6a-dfd0-49a6-beea-77326a4e13aa
Content-Type: application/json

{
	"price": 6
}

###
DELETE http://localhost:3100/shop/cards/1ade0a6a-dfd0-49a6-beea-77326a4e13aa

###
POST http://localhost:3100/shop/cards/9b5a14eb-7f0b-4ad8-ae54-c3a9e97f2d1b/purchase
