GET http://localhost:3100/user/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1M2ExMGFkNS01YzdhLTQ0MTUtOTY4My1hMTUxYjg2MWIyNmQiLCJpYXQiOjE3MzI1ODkwMjcsImV4cCI6MTczMjY3NTQyN30.SRiVx0jX68f_MIbKY4RlP9NyAMMNlCcWJJ1xWnXl3sI

###
# GET http://localhost:3100/user/cards?userId=53a10ad5-5c7a-4415-9683-a151b861b26d&page=1&pageSize=10&orderBy=priceLowest&filter[type]=type&filter[value]=물
GET http://localhost:3100/user/cards?&page=1&pageSize=10&orderBy=priceLowest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1M2ExMGFkNS01YzdhLTQ0MTUtOTY4My1hMTUxYjg2MWIyNmQiLCJpYXQiOjE3MzI1ODkwMjcsImV4cCI6MTczMjY3NTQyN30.SRiVx0jX68f_MIbKY4RlP9NyAMMNlCcWJJ1xWnXl3sI
###
POST http://localhost:3100/auth/login
Content-Type: application/json

{
	"email": "test2@hanmail.com",
	"password": "1234"
}