name: Pull Request

on:
  pull_request:
    types: [review_requested]

jobs:
  specific_review_requested:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 리포지토리 체크아웃
      - uses: actions/checkout@v3

      # 2. 리뷰어 목록 가져오기
      - name: Get Reviewers List
        id: reviewers
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = '.github/workflows/reviewers.json'; // reviewers.json 파일 경로
            const workers = JSON.parse(fs.readFileSync(path, 'utf8')); // 파일 읽기
            const mention = context.payload.pull_request.requested_reviewers.map((user) => {
              const login = user.login;
              const mappedValue = workers[login];
              return mappedValue ? `<@${mappedValue}>` : `No mapping found for ${login}`;
            });
            core.setOutput('result', mention.join(', ')); // 슬랙 멘션 리스트 출력

      # 3. Slack 알림 전송
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.TEST_CHANNEL }}
          payload: |
            {
              "text": "PR Review Request",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "리뷰어로 할당되었습니다.\n • 제목: *${{ github.event.pull_request.title }}*\n • 리뷰어: ${{ steps.reviewers.outputs.result }}\n • 링크: <${{ github.event.pull_request.html_url }}|리뷰하러 가기>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
