name: Pull request

on:
  pull_request:
    types: [review_requested] # 리뷰 요청된 이벤트 감지

jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    steps: # 작업 단계 정의
      - name: reviewer 되면 slack 알림 보냄
        uses: slackapi/slack-github-action@v1.24.0 # slack 액션 사용
        with:
          channel-id: ${{ secrets.BE_CHANNEL}} # slack 채널 ID를 비밀로 설정
          payload: |
            {
              "text": "pr review request",

              "blocks": [
                {
                 "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    
                    "text": 리뷰어로 할당되었습니다.\\\\n • 제목: PR 제목\\n • 리뷰어: @리뷰어 \\n • 링크: 리뷰 링크" # 메시지의 내용을 설정합니다.
                  }
                }
              ] 
            }
        env:
          SLACK_BOT_TOKEN: ${{secrets.TSET_BOT_TOKEN}}
